<a href="https://colab.research.google.com/github/kulshresthavanya3-prog/DATA-ANALYST-INTERN-AT-ELEVATE-LABS/blob/main/TASK1_COMPLETED(By_Vanya_Kulshrestha).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import os

print(os.getcwd())

/content

In [14]:
print(os.listdir())

['.config', 'sample_data']

In [17]:
from google.colab import files

uploaded = files.upload()

Saving sales_data.csv to sales_data.csv

In [18]:
import pandas as pd

data = pd.read_csv('sales_data.csv')

print(data.head())

   Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
0        1052  2023-02-03       Bob  North       5053.97             18
1        1093  2023-04-21       Bob   West       4384.02             17
2        1015  2023-09-21     David  South       4631.23             30
3        1072  2023-08-24       Bob  South       2167.94             39
4        1061  2023-03-24   Charlie   East       3750.20             13

  Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
0        Furniture     152.75      267.22     Returning      0.09
1        Furniture    3816.39     4209.44     Returning      0.11
2             Food     261.56      371.40     Returning      0.20
3         Clothing    4330.03     4467.75           New      0.02
4      Electronics     637.37      692.71           New      0.08

  Payment_Method Sales_Channel Region_and_Sales_Rep
0           Cash        Online            North-Bob
1           Cash        Retail             West-Bob
2  Bank Transfer        Retail          South-David
3    Credit Card        Retail            South-Bob
4    Credit Card        Online         East-Charlie

In [21]:
import pandas as pd

print(data.info())
print(data.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Product_ID            1000 non-null   int64
 1   Sale_Date             1000 non-null   object
 2   Sales_Rep             1000 non-null   object
 3   Region                1000 non-null   object
 4   Sales_Amount          1000 non-null   float64
 5   Quantity_Sold         1000 non-null   int64
 6   Product_Category      1000 non-null   object
 7   Unit_Cost             1000 non-null   float64
 8   Unit_Price            1000 non-null   float64
 9   Customer_Type         1000 non-null   object
 10  Discount              1000 non-null   float64
 11  Payment_Method        1000 non-null   object
 12  Sales_Channel         1000 non-null   object
 13  Region_and_Sales_Rep  1000 non-null   object
dtypes: float64(4), int64(2), object(8)
memory usage: 109.5+ KB
None
Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

In [22]:
print(data.duplicated().sum())

0

In [41]:
data.describe()

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount,profit
count,761.000000,761.000000,761.000000,761.000000,761.000000,761.000000,761.000000
mean,1050.239159,4939.600591,25.545335,2496.658844,2750.348134,0.154573,2442.941748
std,29.412146,2866.189176,14.156767,1420.096079,1419.943363,0.084756,3185.378223
min,1001.000000,100.120000,1.000000,60.280000,167.120000,0.010000,-4793.560000
25%,1024.000000,2381.120000,14.000000,1296.440000,1528.400000,0.080000,70.630000
50%,1051.000000,4896.930000,26.000000,2495.200000,2723.130000,0.150000,2382.720000
75%,1075.000000,7370.990000,38.000000,3741.300000,4004.000000,0.230000,4935.740000
max,1100.000000,9976.520000,49.000000,4991.680000,5309.320000,0.300000,9514.560000

In [30]:
data = data.drop('Region', axis=1)

In [33]:
data['profit'] = data['Sales_Amount'] - data['Unit_Cost']

In [34]:
data.head(5)

,Product_ID,Sale_Date,Sales_Rep,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,profit
0,1052,2023-02-03,Bob,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,4901.22
1,1093,2023-04-21,Bob,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,567.63
2,1015,2023-09-21,David,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,4369.67
3,1072,2023-08-24,Bob,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,-2162.09
4,1061,2023-03-24,Charlie,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,3112.83

In [35]:
print(data.dtypes)

Product_ID            int64
Sale_Date            object
Sales_Rep            object
Sales_Amount        float64
Quantity_Sold         int64
Product_Category     object
Unit_Cost           float64
Unit_Price          float64
Customer_Type        object
Discount            float64
Payment_Method       object
Sales_Channel        object
profit              float64
dtype: object

In [36]:
data = data[data['Product_Category'] != 'Food']

In [37]:
data = data[data['Discount'] !=0]

In [39]:
data['Payment_Method'] = data['Payment_Method'].astype('string')

In [40]:
data['Sales_Channel'] = data['Sales_Channel'].astype('string')

In [45]:
data['Sale_Date'] = pd.to_datetime(data['Sale_Date']).dt.strftime('%d-%m-%Y')

In [46]:
data.head(5)

,Product_ID,Sale_Date,Sales_Rep,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,profit
0,1052,03-02-2023,Bob,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,4901.22
1,1093,21-04-2023,Bob,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,567.63
3,1072,24-08-2023,Bob,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,-2162.09
4,1061,24-03-2023,Charlie,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,3112.83
6,1083,11-04-2023,Bob,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,-1790.50